// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment('WEB_API_KEY'),
    appId: String.fromEnvironment('WEB_APP_ID'),
    messagingSenderId: String.fromEnvironment('WEB_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('WEB_PROJECT_ID'),
    authDomain: String.fromEnvironment('WEB_AUTH_DOMAIN'),
    storageBucket: String.fromEnvironment('WEB_STORAGE_BUCKET'),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment('ANDROID_API_KEY'),
    appId: String.fromEnvironment('ANDROID_APP_ID'),
    messagingSenderId: String.fromEnvironment('ANDROID_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('ANDROID_PROJECT_ID'),
    storageBucket: String.fromEnvironment('ANDROID_STORAGE_BUCKET'),
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment('IOS_API_KEY'),
    appId: String.fromEnvironment('IOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('IOS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('IOS_PROJECT_ID'),
    storageBucket: String.fromEnvironment('IOS_STORAGE_BUCKET'),
    iosClientId: String.fromEnvironment('IOS_CLIENT_ID'),
    iosBundleId: String.fromEnvironment('IOS_BUNDLE_ID'),
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment('MACOS_API_KEY'),
    appId: String.fromEnvironment('MACOS_APP_ID'),
    messagingSenderId: String.fromEnvironment('MACOS_MESSAGING_SENDER_ID'),
    projectId: String.fromEnvironment('MACOS_PROJECT_ID'),
    storageBucket: String.fromEnvironment('MACOS_STORAGE_BUCKET'),
    iosClientId: String.fromEnvironment('MACOS_CLIENT_ID'),
    iosBundleId: String.fromEnvironment('MACOS_BUNDLE_ID'),
  );
}
